version: '3.7'

# starts 1 minio server instance docker container.
# using nginx reverse proxy, you can access
# it through default port 9000.
services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-06-30T20-58-09Z
    command: server http://minio /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASS:-minio123}
      MINIO_BROWSER_REDIRECT_URL: https://${FQDN}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    volumes:
      - data:/data

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/templates:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    environment:
      - NGINX_HOST=${FQDN}
    ports:
      - "443:443"
      - "9000:9000"
    depends_on:
      - minio
      - certbot
    restart: always

  certbot:
    image: certbot/certbot
    ports:
      - "80:80"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    command: certonly --standalone --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${FQDN}

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data:
  certbot-etc:
  certbot-var:
